export default {
  key: 'caz-and-dan',
  slug: 'caz-and-dan',
  title: 'Caz & Dan',
  shortTitle: 'Caz & Dan',
  maxShots: 25,
  theme: 'elegant',
  heroImage: null,
  dateLabel: '10.10.26',
  intro: 'Twenty-five disposable-camera shots to capture the day exactly as it happens.',
  cameraIntro: 'No previews and no retakes — just point, shoot and enjoy the moment.',
  finishedTitle: 'That’s a wrap',
  finishedCopy: 'Your photographs are safely stored and will be ready for the gallery.',
  palette: {
    background: '#ece9df',
    surface: '#f8f6ef',
    surfaceStrong: '#dedfce',
    ink: '#151515',
    muted: '#696b60',
    accent: '#747c58',
    accentDark: '#4e5539',
    sand: '#c7c2b2',
    line: '#171717',
    camera: '#11120f',
  },
}
